### ISSUE TITLE
Erreur instalation PIP

### ISSUE THREAD

**Issue by code404nul** [yoyoberenguer/PygameShader#10]
**Describe the bug**
i can't install fewer version

PS C:\Users\tatat\python\pour les autres\challenge> pip install PygameShader==1.0.2
Defaulting to user installation because normal site-packages is not writeable
Collecting PygameShader==1.0.2
  Downloading PygameShader-1.0.2.tar.gz (2.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB 9.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: setuptools>=49.2.1 in c:\users\tatat\appdata\roaming\python\python312\site-packages (from PygameShader==1.0.2) (70.1.0)
Requirement already satisfied: Cython>=0.28 in c:\users\tatat\appdata\roaming\python\python312\site-packages (from PygameShader==1.0.2) (3.0.11)      
Requirement already satisfied: numpy>=1.18 in c:\users\tatat\appdata\roaming\python\python312\site-packages (from PygameShader==1.0.2) (1.26.4)       
Requirement already satisfied: pygame>=2.0 in c:\users\tatat\appdata\roaming\python\python312\site-packages (from PygameShader==1.0.2) (2.6.0)        
Building wheels for collected packages: PygameShader
  Building wheel for PygameShader (pyproject.toml) ... done
  Created wheel for PygameShader: filename=PygameShader-1.0.2-cp312-cp312-win_amd64.whl size=5255595 sha256=474258718424c1f93a1dfea6537f99bef613cfcc78f13ae1a89331affc0984c3
  Stored in directory: c:\users\tatat\appdata\local\pip\cache\wheels\ad\f4\85\0fd3a03dc41d5f40fa3084a2ce3a67bf0c298fbedd4384d71b
Successfully built PygameShader
Installing collected packages: PygameShader
  Attempting uninstall: PygameShader
    Found existing installation: PygameShader 1.0.1
    Uninstalling PygameShader-1.0.1:
      Successfully uninstalled PygameShader-1.0.1
Successfully installed PygameShader-1.0.2
PS C:\Users\tatat\python\pour les autres\challenge> pip install PygameShader==1.0.3
Defaulting to user installation because normal site-packages is not writeable
Collecting PygameShader==1.0.3
  Using cached PygameShader-1.0.3.tar.gz (7.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [115 lines of output]
      C:\Users\tatat\AppData\Local\Temp\pip-build-env-awkc42_k\overlay\Lib\site-packages\Cython\Compiler\Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: C:\Users\tatat\AppData\Local\Temp\pip-install-dscuhpw2\pygameshader_2f403ced51234fe0b943e55352dc5344\PygameShader\Palette.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      C:\Users\tatat\AppData\Local\Temp\pip-build-env-awkc42_k\overlay\Lib\site-packages\Cython\Compiler\Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: C:\Users\tatat\AppData\Local\Temp\pip-install-dscuhpw2\pygameshader_2f403ced51234fe0b943e55352dc5344\PygameShader\gaussianBlur5x5.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      C:\Users\tatat\AppData\Local\Temp\pip-build-env-awkc42_k\overlay\Lib\site-packages\Cython\Compiler\Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: C:\Users\tatat\AppData\Local\Temp\pip-install-dscuhpw2\pygameshader_2f403ced51234fe0b943e55352dc5344\PygameShader\misc.pxd
        tree = Parsing.p_module(s, pxd, full_module_name)

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              add, putmask, int16, arange, repeat, newaxis
      except ImportError:
          raise ImportError("\n<numpy> library is missing on your system."
                "\nTry: \n   C:\\pip install numpy on a window command prompt.")

      from shader cimport hsv, rgb, minf, struct_rgb_to_hsv
      ^
      ------------------------------------------------------------

      PygameShader\misc.pyx:65:0: 'shader.pxd' not found

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              add, putmask, int16, arange, repeat, newaxis
      except ImportError:
          raise ImportError("\n<numpy> library is missing on your system."
                "\nTry: \n   C:\\pip install numpy on a window command prompt.")

      from shader cimport hsv, rgb, minf, struct_rgb_to_hsv
      ^
      ------------------------------------------------------------

      PygameShader\misc.pyx:65:0: 'shader\hsv.pxd' not found

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              add, putmask, int16, arange, repeat, newaxis
      except ImportError:
          raise ImportError("\n<numpy> library is missing on your system."
                "\nTry: \n   C:\\pip install numpy on a window command prompt.")

      from shader cimport hsv, rgb, minf, struct_rgb_to_hsv
      ^
      ------------------------------------------------------------

      PygameShader\misc.pyx:65:0: 'shader\rgb.pxd' not found

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              add, putmask, int16, arange, repeat, newaxis
      except ImportError:
          raise ImportError("\n<numpy> library is missing on your system."
                "\nTry: \n   C:\\pip install numpy on a window command prompt.")

      from shader cimport hsv, rgb, minf, struct_rgb_to_hsv
      ^
      ------------------------------------------------------------

      PygameShader\misc.pyx:65:0: 'shader\minf.pxd' not found

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              add, putmask, int16, arange, repeat, newaxis
      except ImportError:
          raise ImportError("\n<numpy> library is missing on your system."
                "\nTry: \n   C:\\pip install numpy on a window command prompt.")

      from shader cimport hsv, rgb, minf, struct_rgb_to_hsv
      ^
      ------------------------------------------------------------

      PygameShader\misc.pyx:65:0: 'shader\struct_rgb_to_hsv.pxd' not found
      performance hint: PygameShader\misc.pxd:63:25: No exception value declared for 'color_dist_hsv' in pxd file.
      Users cimporting this function and calling it without the gil will always require an exception check.
      Suggest adding an explicit exception value.
      performance hint: PygameShader\misc.pxd:64:25: No exception value declared for 'color_dist_hsl' in pxd file.
      Users cimporting this function and calling it without the gil will always require an exception check.
      Suggest adding an explicit exception value.
      performance hint: PygameShader\misc.pyx:254:5: Exception check on 'color_diff_hsv' will always require the GIL to be acquired. Declare 'color_diff_hsv' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: PygameShader\misc.pyx:326:5: Exception check on 'color_diff_hsl' will always require the GIL to be acquired. Declare 'color_diff_hsl' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: PygameShader\misc.pyx:397:5: Exception check on 'close_color' will always require the GIL to be acquired. Declare 'close_color' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: PygameShader\misc.pyx:492:5: Exception check on 'use_palette' will always require the GIL to be acquired. Declare 'use_palette' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      Compiling PygameShader/shader.pyx because it changed.
      Compiling PygameShader/misc.pyx because it changed.
      Compiling PygameShader/gaussianBlur5x5.pyx because it changed.
      Compiling PygameShader/Palette.pyx because it changed.
      [1/4] Cythonizing PygameShader/Palette.pyx
      [2/4] Cythonizing PygameShader/gaussianBlur5x5.pyx
      [3/4] Cythonizing PygameShader/misc.pyx
      Traceback (most recent call last):
        File "C:\Users\tatat\AppData\Roaming\Python\Python312\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\tatat\AppData\Roaming\Python\Python312\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\tatat\AppData\Roaming\Python\Python312\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\tatat\AppData\Local\Temp\pip-build-env-awkc42_k\overlay\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\tatat\AppData\Local\Temp\pip-build-env-awkc42_k\overlay\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "C:\Users\tatat\AppData\Local\Temp\pip-build-env-awkc42_k\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup    
          exec(code, locals())
        File "<string>", line 43, in <module>
        File "C:\Users\tatat\AppData\Local\Temp\pip-build-env-awkc42_k\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "C:\Users\tatat\AppData\Local\Temp\pip-build-env-awkc42_k\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: PygameShader/misc.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by yoyoberenguer** [comment]
`PygameShader` Versions [1.0.2 - 1.0.8] are available and compatible with Python 3.6 to 3.10 only.
The setup.py file does not restrict the user to install the project from newest python version >=3.11 (which is your case). 
This was corrected in the latest version of `PygameShader` by introducing checks upon the Python version being used.
Wheel's packages on PIP support those versions and I believe that you should be able to install PygameShader version 1.0.3 using python < 3.11

An additional source file is available to build the project from source, however the version 1.0.3 was designed and uploaded to PIP before the apparition of python 3.11 and therefore never been tested for compatibility.

Available work around 
1 - you can install the latest `PygameShader` version 1.0.10. wheels packages are available for most platforms using Python 3.11 
2 - You can download the source file from PIP (tar.gz file) available here 
```
https://pypi.org/project/PygameShader/1.0.3/#files
```
And build the project manually using Cython == 0.29.37 with Pyton 3.11
```
pip311 install Cython==0.29.37
python311 setup.py build_ext --inplace
python311 setup.py bdist_wheel
```
Once the wheel is ready
```
cd dist 
pip311 install PygameShader-xxxxxx 
```

such as below 
![image](https://github.com/user-attachments/assets/845aed57-c207-4d5d-b39e-50fbd26052cb)

After installation
![image](https://github.com/user-attachments/assets/ecf0a1cb-dc07-4715-a273-d51a721cbde9)

Checks 
![image](https://github.com/user-attachments/assets/3c01df70-cd96-4a9c-a0b8-a7c3d9742d7b)

In the mean time I will upload the wheel packages to PIP for python 3.11 for 32-bit and 64-bit processor and Linux / MAC at first opportunity. 

However, as general guideline I would highly recommended to install the latest version.
