### ISSUE TITLE
PygameShader shader bloom on more platforms

### ISSUE THREAD

**Issue by ikvk** [yoyoberenguer/PygameShader#8]
Greetengs.

**Is your feature request related to a problem? Please describe.**
I have tried to use bloom on android device.

`from PygameShader.shader import bloom`

Builds with p4a apk: (python-for-android==2023.5.21)
```
  --arch=arm64-v8a \
  --arch=armeabi-v7a \
```
and got:
```
I/python: Traceback (most recent call last):
I/python:   File "/home/kvk/proj1/main.py", line 10, in <module>
I/python:   File "/home/kvk/proj1/fall/systems.py", line 18, in <module>
I/python:   File "/home/kvk/proj1/fall/sprites.py", line 10, in <module>
I/python:   File "/home/kvk/.local/share/python-for-android/build/python-installs/proj1_fall/arm64-v8a/PygameShader/__init__.py", line 4, in <module>
I/python: ImportError: dlopen failed: "/data/data/game.ikvk.trigfall/files/app/_python_bundle/site-packages/PygameShader/shader.so" has unexpected e_machine: 62 (EM_X86_64)
I/python: Python for android ended.
```

**Describe the solution you'd like**
Implement it on more archs (as I understand it is possible)

**Describe alternatives you've considered**
May be I am doing somesthing wrong?

**Additional context**
xiaomi mi 6 android phone

**Comment by yoyoberenguer** [comment]
Hi and thank you for taking the time to report this, 
This essentially means that PygameShader is built with X86_64 architecture support and you are trying to load it on 
 --arch=arm64-v8a  or  --arch=armeabi-v7a. 
I am yet to do some internal testing to check if the project can be ported to mobile architecture armeabi-v7a or arm64-v8a
Kind Regards
